# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/a-user0/projects/cpp/debugger_linux

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/a-user0/projects/cpp/debugger_linux

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/a-user0/projects/cpp/debugger_linux/CMakeFiles /home/a-user0/projects/cpp/debugger_linux//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/a-user0/projects/cpp/debugger_linux/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dbg

# Build rule for target.
dbg: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 dbg
.PHONY : dbg

# fast build rule for target.
dbg/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbg.dir/build.make CMakeFiles/dbg.dir/build
.PHONY : dbg/fast

exts/linenoise/linenoise.o: exts/linenoise/linenoise.c.o
.PHONY : exts/linenoise/linenoise.o

# target to build an object file
exts/linenoise/linenoise.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbg.dir/build.make CMakeFiles/dbg.dir/exts/linenoise/linenoise.c.o
.PHONY : exts/linenoise/linenoise.c.o

exts/linenoise/linenoise.i: exts/linenoise/linenoise.c.i
.PHONY : exts/linenoise/linenoise.i

# target to preprocess a source file
exts/linenoise/linenoise.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbg.dir/build.make CMakeFiles/dbg.dir/exts/linenoise/linenoise.c.i
.PHONY : exts/linenoise/linenoise.c.i

exts/linenoise/linenoise.s: exts/linenoise/linenoise.c.s
.PHONY : exts/linenoise/linenoise.s

# target to generate assembly for a file
exts/linenoise/linenoise.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbg.dir/build.make CMakeFiles/dbg.dir/exts/linenoise/linenoise.c.s
.PHONY : exts/linenoise/linenoise.c.s

src/breakpoint.o: src/breakpoint.cc.o
.PHONY : src/breakpoint.o

# target to build an object file
src/breakpoint.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbg.dir/build.make CMakeFiles/dbg.dir/src/breakpoint.cc.o
.PHONY : src/breakpoint.cc.o

src/breakpoint.i: src/breakpoint.cc.i
.PHONY : src/breakpoint.i

# target to preprocess a source file
src/breakpoint.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbg.dir/build.make CMakeFiles/dbg.dir/src/breakpoint.cc.i
.PHONY : src/breakpoint.cc.i

src/breakpoint.s: src/breakpoint.cc.s
.PHONY : src/breakpoint.s

# target to generate assembly for a file
src/breakpoint.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbg.dir/build.make CMakeFiles/dbg.dir/src/breakpoint.cc.s
.PHONY : src/breakpoint.cc.s

src/debugger.o: src/debugger.cc.o
.PHONY : src/debugger.o

# target to build an object file
src/debugger.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbg.dir/build.make CMakeFiles/dbg.dir/src/debugger.cc.o
.PHONY : src/debugger.cc.o

src/debugger.i: src/debugger.cc.i
.PHONY : src/debugger.i

# target to preprocess a source file
src/debugger.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbg.dir/build.make CMakeFiles/dbg.dir/src/debugger.cc.i
.PHONY : src/debugger.cc.i

src/debugger.s: src/debugger.cc.s
.PHONY : src/debugger.s

# target to generate assembly for a file
src/debugger.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbg.dir/build.make CMakeFiles/dbg.dir/src/debugger.cc.s
.PHONY : src/debugger.cc.s

src/main.o: src/main.cc.o
.PHONY : src/main.o

# target to build an object file
src/main.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbg.dir/build.make CMakeFiles/dbg.dir/src/main.cc.o
.PHONY : src/main.cc.o

src/main.i: src/main.cc.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbg.dir/build.make CMakeFiles/dbg.dir/src/main.cc.i
.PHONY : src/main.cc.i

src/main.s: src/main.cc.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbg.dir/build.make CMakeFiles/dbg.dir/src/main.cc.s
.PHONY : src/main.cc.s

src/registers.o: src/registers.cc.o
.PHONY : src/registers.o

# target to build an object file
src/registers.cc.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbg.dir/build.make CMakeFiles/dbg.dir/src/registers.cc.o
.PHONY : src/registers.cc.o

src/registers.i: src/registers.cc.i
.PHONY : src/registers.i

# target to preprocess a source file
src/registers.cc.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbg.dir/build.make CMakeFiles/dbg.dir/src/registers.cc.i
.PHONY : src/registers.cc.i

src/registers.s: src/registers.cc.s
.PHONY : src/registers.s

# target to generate assembly for a file
src/registers.cc.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/dbg.dir/build.make CMakeFiles/dbg.dir/src/registers.cc.s
.PHONY : src/registers.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... dbg"
	@echo "... exts/linenoise/linenoise.o"
	@echo "... exts/linenoise/linenoise.i"
	@echo "... exts/linenoise/linenoise.s"
	@echo "... src/breakpoint.o"
	@echo "... src/breakpoint.i"
	@echo "... src/breakpoint.s"
	@echo "... src/debugger.o"
	@echo "... src/debugger.i"
	@echo "... src/debugger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/registers.o"
	@echo "... src/registers.i"
	@echo "... src/registers.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

